### PR TITLE
Bug #68 - Wrap nullable values in Optional to avoid InvalidCacheLoadException from Guava cache

### PR DESCRIPTION
**Pull request by jhinch**
I'm currently working with the 1.0.x series. Would you be happy to receive a back port fix for that as well?

### CODE REVIEW

**Comment by jkodumal** [comment]
👍 we can take a back-port as well. Thanks!

**Comment by jhinch** [comment]
Backport PR created at #70

**Comment by jkodumal** [comment]
@drichelson thoughts or thumbs?

**Comment by drichelson** [comment]
👍

**Pull request merged**
