### PR TITLE
Pk/ms timeouts

### PR DESCRIPTION
**Pull request by pkaeding**
Also got circleci builds working

### CODE REVIEW

**Comment by jkodumal** [comment]
This is an API breaking change, so we'd need to do a major release. Also the docs need to be updated.

**Comment by pkaeding** [comment]
Yeah, that's right. I meant to mention that.

**Comment by pkaeding** [comment]
Okay, these latest changes maintain backwards compatibility, and allow you to specify the timeouts in either seconds or milliseconds.  This will be a minor release.

**Comment by jkodumal** [comment]
lgtm

**Pull request merged**
